"""create tables

Revision ID: ddf7fa380693
Revises: 
Create Date: 2024-03-05 15:53:28.399687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf7fa380693'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interventionrecords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('images', sa.String(), nullable=True),
    sa.Column('videos', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name=op.f('fk_interventionrecords_users_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redflagrecords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('images', sa.String(), nullable=True),
    sa.Column('videos', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name=op.f('fk_redflagrecords_users_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adminactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redflagrecords_id', sa.Integer(), nullable=False),
    sa.Column('interventionrecords_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interventionrecords_id'], ['interventionrecords.id'], name=op.f('fk_adminactions_interventionrecords_id_interventionrecords')),
    sa.ForeignKeyConstraint(['redflagrecords_id'], ['redflagrecords.id'], name=op.f('fk_adminactions_redflagrecords_id_redflagrecords')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adminactions')
    op.drop_table('redflagrecords')
    op.drop_table('interventionrecords')
    op.drop_table('users')
    # ### end Alembic commands ###
