"""empty message

Revision ID: fcc78da94298
Revises: ddf7fa380693
Create Date: 2024-03-05 17:44:44.658831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc78da94298'
down_revision = 'ddf7fa380693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interventionrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('images', sa.String(), nullable=True),
    sa.Column('videos', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['user.id'], name=op.f('fk_interventionrecord_users_id_user')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redflagrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('images', sa.String(), nullable=True),
    sa.Column('videos', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['user.id'], name=op.f('fk_redflagrecord_users_id_user')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adminaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redflagrecords_id', sa.Integer(), nullable=False),
    sa.Column('interventionrecords_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interventionrecords_id'], ['interventionrecord.id'], name=op.f('fk_adminaction_interventionrecords_id_interventionrecord')),
    sa.ForeignKeyConstraint(['redflagrecords_id'], ['redflagrecord.id'], name=op.f('fk_adminaction_redflagrecords_id_redflagrecord')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('redflagrecords')
    op.drop_table('interventionrecords')
    op.drop_table('adminactions')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adminactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('redflagrecords_id', sa.INTEGER(), nullable=False),
    sa.Column('interventionrecords_id', sa.INTEGER(), nullable=False),
    sa.Column('action_type', sa.VARCHAR(), nullable=True),
    sa.Column('comments', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['interventionrecords_id'], ['interventionrecords.id'], name='fk_adminactions_interventionrecords_id_interventionrecords'),
    sa.ForeignKeyConstraint(['redflagrecords_id'], ['redflagrecords.id'], name='fk_adminactions_redflagrecords_id_redflagrecords'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interventionrecords',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('users_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('images', sa.VARCHAR(), nullable=True),
    sa.Column('videos', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='fk_interventionrecords_users_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redflagrecords',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('users_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('images', sa.VARCHAR(), nullable=True),
    sa.Column('videos', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='fk_redflagrecords_users_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('adminaction')
    op.drop_table('redflagrecord')
    op.drop_table('interventionrecord')
    op.drop_table('user')
    # ### end Alembic commands ###
